import "../styles/global.css";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};
import { Header } from "./components/Header";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className="h-min-screen flex justify-center items-center">
        <main className="min-h-screen p-2 w-fit space-y-2">
          <Header />
          <section className="flex justify-center h-full gap-8">{children}
          </section>
        </main>
      </body>
    </html>
  );
}
